# -*- coding: utf-8 -*-
"""IsolationForest_in_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjVbs_XIbdWDmVVMyO6VAn2G4U1Cu7jv

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html </br>
https://github.com/scikit-learn/scikit-learn/blob/fe2edb3cd/sklearn/ensemble/_iforest.py#L55 </br>
https://www.geeksforgeeks.org/machine-learning/what-is-isolation-forest/ </br>
https://www.datacamp.com/tutorial/isolation-forest </br>
https://pyimagesearch.com/2024/10/21/predictive-maintenance-using-isolation-forest/

# **IsolationForest** </br>

1) class sklearn.ensemble.IsolationForest(*, n_estimators=100, max_samples='auto', contamination='auto', max_features=1.0, bootstrap=False, n_jobs=None, random_state=None, verbose=0, warm_start=False)
</br>
2) (i) Return the anomaly score of each sample using the *IsolationForest* algorithm. (ii) The IsolationForest ‘isolates’ observations by randomly selecting a feature and then randomly selecting a split value between the maximum and minimum values of the selected feature. (iii) Partitioning: Data is split using randomly selected features and random threshold values. These random splits efficiently separate anomalies from normal data. (iv) Anomaly Score: The anomaly score represents how easily a data point can be isolated. Fewer splits mean a higher anomaly score, hence a greater likelihood of being an outlier.
"""

#Importing required libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

"""#Load Sample Dataset & Pre-processing

(1) A Credit Card Anomaly detection dataset (284,808 rows) for its implementation and limit its row count to 40,000 for faster processing. </br>
(2) Standardise the features of the dataset excluding the target variable 'Class' using StandardScaler.
"""

credit_data = pd.read_csv('/content/creditcard.csv', nrows=40000)
#Dataset can be downloaded from https://www.geeksforgeeks.org/machine-learning/what-is-isolation-forest/

scaler = StandardScaler().fit_transform(credit_data.loc[:,credit_data.columns!='Class'])
scaled_data = scaler[0:40000]
df = pd.DataFrame(data=scaled_data)
X = credit_data.drop(columns=['Class'])
y = credit_data['Class']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(X)

"""#Model Making

The fraction of outliers is calculated by looking at the number of fraudulent transactions in the dataset then we create and fit the Isolation Forest model with this outlier fraction. </br>

*   n_estimators=100: Number of trees in the ensemble (improves accuracy).
*   contamination: Fraction of outliers in data, helps model set detection threshold.
* sample_size is the number of instances used to train each Isolation Tree. A value of 256 is commonly used as it allows us to avoid using a maximum tree size stopping criteria. This is because we can expect reasonable maximum tree sizes of log(256) = 8.
* random_state=42: Ensures reproducible results.
"""

### Train the Isolation Forest

outlier_fraction = len(credit_data[credit_data['Class']==1])/float(len(credit_data[credit_data['Class']==0]))
#sample_size = 256

#model =  IsolationForest(n_estimators=100, contamination=outlier_fraction, max_samples=sample_size, random_state=42)
model =  IsolationForest(n_estimators=100, contamination=outlier_fraction, random_state=42)
model.fit(x_train)

"""#Model Making

Evaluate the model’s performance by calculating its accuracy in detecting anomalies (fraudulent transactions) based on the anomaly scores.



*   Decision Function: Computes anomaly scores for each point.
*   Prediction Adjustment: Converts predictions (1 = normal, -1 = anomaly) to match dataset labels.
* Accuracy Calculation: Measures detection rate of anomalies.
"""

scores_prediction = model.decision_function(x_train)
print(scores_prediction)

y_pred = model.predict(x_test)
y_pred[y_pred == 1] = 0
y_pred[y_pred == -1] = 1

print("Accuracy in finding anomaly:",accuracy_score(y_test, y_pred))

# Visualise the model

y_feature = x_test['Amount']
x_test['predicted_class'] = y_pred

plt.figure(figsize=(7, 4))
sns.scatterplot(x=credit_data.index, y=y_feature, hue=credit_data['predicted_class'], palette={0: 'blue', 1: 'red'}, s=50)
plt.title('Visualisation of Normal vs Anomalous Transactions')
plt.xlabel('Data points')
plt.ylabel(y_feature.name)
plt.legend(title='Predicted Class', loc='best')
plt.show()